version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - echo Building the React.js project
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  # If type is set to S3, this is the name of the output artifact object.
  # If you set the name to be a forward slash ("/"),
  # the artifact is stored in the root of the output bucket.
  name: /
  files:
    - build/**/*
