version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - echo Building the React.js project
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  name: homework-app
  files:
    - build/**/*
  base-directory: build
