version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn install
  build:
    commands:
      - echo Building the React.js project
      - yarn build

artifacts:
  name: .
  files:
    - "**/*"
  base-directory: build
